# This Dockerfile is a used by CI to publish an installer image for creating libvirt clusters
# It builds an image containing openshift-install and nss-wrapper for remote deployments, as well as the google cloud-sdk for nested GCE environments.

FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.15-openshift-4.8 AS builder
ARG TAGS="libvirt"
RUN yum install -y libvirt-devel && \
    yum clean all && rm -rf /var/cache/yum/*
WORKDIR /go/src/github.com/openshift/installer
COPY . .
RUN hack/build.sh

FROM registry.ci.openshift.org/origin/4.8:base
COPY --from=builder /go/src/github.com/openshift/installer/bin/openshift-install /bin/openshift-install

RUN yum install --setopt=tsflags=nodocs -y \
    libvirt-client \
    libvirt-libs && \
    yum clean all && rm -rf /var/cache/yum/*

RUN mkdir /output && chown 1000:1000 /output
USER 1000:1000
ENV PATH /bin
ENV HOME /output
WORKDIR /output
# We're not really an operator, we're just getting some data into the release image.
LABEL io.openshift.release.operator=true
ENTRYPOINT ["/bin/openshift-install"]
